version: "2.1"

services:
  php-8.0:
    build:
      context: .
      dockerfile: docker/php-8.0/Dockerfile
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - ./src:/var/www/html/src
      - ./tests:/var/www/html/tests

  php-8.1:
    extends:
      service: php-8.0
    build:
      dockerfile: docker/php-8.1/Dockerfile

  app:
    extends:
      service: php-8.1
    volumes:
      - .:/var/www/html
