services:
  php-8.2:
    build:
      context: .
      dockerfile: docker/php-8.2/Dockerfile
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - ./src:/var/www/html/src
      - ./tests:/var/www/html/tests

  php-8.3:
    extends:
      service: php-8.2
    build:
      dockerfile: docker/php-8.3/Dockerfile

  app:
    extends:
      service: php-8.2
    volumes:
      - .:/var/www/html
